server:
  port: 9090


spring:
  datasource:
    url: jdbc:postgresql://4a898a747904:5432/YarismaDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

